# Generated by Django 4.1 on 2022-08-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='User_pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
